In [30]:
import pandas as pd
df = pd.read_pickle("household_data.pkl")
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [31]:
df['Sub_metering_3'] = pd.to_numeric(df['Sub_metering_3'], errors='coerce')
df['Sub_metering_2'] = pd.to_numeric(df['Sub_metering_2'], errors='coerce')
df['Sub_metering_1'] = pd.to_numeric(df['Sub_metering_1'], errors='coerce')
df['Global_intensity'] = pd.to_numeric(df['Global_intensity'], errors='coerce')
df['Voltage'] = pd.to_numeric(df['Voltage'], errors='coerce')
df['Global_reactive_power'] = pd.to_numeric(df['Global_reactive_power'], errors='coerce')
df['Global_active_power'] = pd.to_numeric(df['Global_active_power'], errors='coerce')

In [32]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [33]:

df['Sub_metering_3']=df['Sub_metering_3'].fillna(df['Sub_metering_3'].mean())

df['Sub_metering_2']=df['Sub_metering_2'].fillna(df['Sub_metering_2'].mean())

df['Sub_metering_1']=df['Sub_metering_1'].fillna(df['Sub_metering_1'].mean())

df['Global_intensity']=df['Global_intensity'].fillna(df['Global_intensity'].mean())

df['Voltage']=df['Voltage'].fillna(df['Voltage'].mean())

df['Global_reactive_power']=df['Global_reactive_power'].fillna(df['Global_reactive_power'].mean())

df['Global_active_power']=df['Global_active_power'].fillna(df['Global_active_power'].mean())

In [34]:
df.isnull().sum()

Date                     0
Time                     0
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
dtype: int64

In [35]:
df['datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], dayfirst=True)
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['minute'] = df['datetime'].dt.minute
df['second']=df['datetime'].dt.second

df['hour'].nunique()

24

In [36]:

df.drop(['Date', 'Time', 'datetime'], axis=1, inplace=True)
df.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,year,month,day,hour,minute,second
0,4.216,0.418,234.84,18.4,0.0,1.0,17.0,2006,12,16,17,24,0
1,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006,12,16,17,25,0
2,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006,12,16,17,26,0
3,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006,12,16,17,27,0
4,3.666,0.528,235.68,15.8,0.0,1.0,17.0,2006,12,16,17,28,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2075254,0.946,0.000,240.43,4.0,0.0,0.0,0.0,2010,11,26,20,58,0
2075255,0.944,0.000,240.00,4.0,0.0,0.0,0.0,2010,11,26,20,59,0
2075256,0.938,0.000,239.82,3.8,0.0,0.0,0.0,2010,11,26,21,0,0
2075257,0.934,0.000,239.70,3.8,0.0,0.0,0.0,2010,11,26,21,1,0
2075258,0.932,0.000,239.55,3.8,0.0,0.0,0.0,2010,11,26,21,2,0

In [37]:
df.duplicated().sum()

np.int64(0)

export the pickle dataframe

In [40]:
pd.to_pickle(df,'household_cleaned_data.pkl')